# -----------------------------------------------------------------------------
# ctx (Build Context)
# -----------------------------------------------------------------------------
FROM scratch AS ctx

COPY build_files /build
COPY system_files /files
COPY cosign.pub /files/etc/pki/containers/zirconium.pub

# -----------------------------------------------------------------------------
# shared-bases
# -----------------------------------------------------------------------------
FROM quay.io/centos/centos:stream10 AS rust-base
RUN dnf -y install epel-release && \
    dnf -y --enablerepo=crb install \
    cargo rust clang git make gcc pkgconf meson ninja-build \
    openssl-devel pam-devel systemd-devel \
    wayland-devel mesa-libgbm-devel libxkbcommon-devel \
    pango-devel cairo-devel glib2-devel pipewire-devel \
    libinput-devel libgudev-devel libseat-devel libdisplay-info-devel \
    xcb-util-cursor-devel libxcb-devel gtk4-devel libseccomp-devel \
    lcms2-devel libheif-devel librsvg2-devel vala \
    gobject-introspection-devel cairo-gobject-devel

FROM quay.io/centos/centos:stream10 AS go-base
RUN dnf -y install golang git make gcc

FROM quay.io/centos/centos:stream10 AS c-base
RUN dnf -y install epel-release && \
    dnf -y --enablerepo=crb install \
    gcc gcc-c++ clang make cmake meson ninja-build autoconf automake libtool git pkgconf \
    systemd-devel wayland-devel wayland-protocols-devel scdoc \
    fontconfig-devel freetype-devel pixman-devel harfbuzz-devel libpng-devel \
    brotli-devel giflib-devel libjpeg-turbo-devel libwebp-devel \
    libxkbcommon-devel check-devel fftw-devel ncurses-devel \
    pulseaudio-libs-devel pipewire-devel alsa-lib-devel SDL2-devel iniparser-devel \
    cli11-devel qt6-qtbase-devel qt6-qtbase-private-devel qt6-qtdeclarative-devel \
    qt6-qtwayland-devel qt6-qtshadertools-devel libdrm-devel polkit-devel \
    jemalloc-devel pam-devel spirv-tools

# -----------------------------------------------------------------------------
# niri
# -----------------------------------------------------------------------------
FROM rust-base AS niri-builder

WORKDIR /build

# clone niri
RUN git clone https://github.com/YaLTeR/niri.git .

# Build niri
RUN cargo build --release

# -----------------------------------------------------------------------------
# dms
# -----------------------------------------------------------------------------
FROM go-base AS dms-builder

WORKDIR /build

RUN git clone https://github.com/AvengeMedia/DankMaterialShell.git .

# Build Core CLI
WORKDIR /build/core
RUN go build -o dms ./cmd/dms

# -----------------------------------------------------------------------------
# dgop
# -----------------------------------------------------------------------------
FROM go-base AS dgop-builder

WORKDIR /build

RUN git clone https://github.com/AvengeMedia/dgop.git .
RUN go build -o dgop ./cmd/cli

# -----------------------------------------------------------------------------
# cliphist
# -----------------------------------------------------------------------------
FROM go-base AS cliphist-builder

WORKDIR /build

RUN git clone https://github.com/sentriz/cliphist.git .
RUN go build -o cliphist .

# -----------------------------------------------------------------------------
# matugen
# -----------------------------------------------------------------------------
FROM rust-base AS matugen-builder

WORKDIR /build

RUN git clone https://github.com/InioX/matugen.git .
RUN cargo build --release

# -----------------------------------------------------------------------------
# wlsunset
# -----------------------------------------------------------------------------
FROM c-base AS wlsunset-builder

WORKDIR /build

RUN git clone https://github.com/kennylevinsen/wlsunset.git .
RUN meson setup build && ninja -C build

# -----------------------------------------------------------------------------
# glycin
# -----------------------------------------------------------------------------
FROM rust-base AS glycin-builder

WORKDIR /build

RUN git clone https://gitlab.gnome.org/GNOME/glycin.git .

RUN meson setup build --prefix=/usr -Dloaders=glycin-heif,glycin-image-rs,glycin-svg && ninja -C build
RUN DESTDIR=/install ninja -C build install

# -----------------------------------------------------------------------------
# libjxl
# -----------------------------------------------------------------------------
FROM c-base AS libjxl-builder

WORKDIR /build

RUN git clone --recursive https://github.com/libjxl/libjxl.git .

RUN cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
RUN cmake --build build --config Release
RUN cmake --install build --config Release --prefix /install/usr

# -----------------------------------------------------------------------------
# quickshell
# -----------------------------------------------------------------------------
FROM c-base AS quickshell-builder

WORKDIR /build

RUN git clone --recursive https://git.outfoxxed.me/quickshell/quickshell.git .

RUN cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCRASH_REPORTER=OFF
RUN cmake --build build
RUN cmake --install build --prefix /install/usr

# -----------------------------------------------------------------------------
# tuigreet
# -----------------------------------------------------------------------------
FROM rust-base AS tuigreet-builder

WORKDIR /build

# clone tuigreet
RUN git clone https://github.com/apognu/tuigreet.git .

# Build tuigreet
RUN cargo build --release

# -----------------------------------------------------------------------------
# xwayland-satellite
# -----------------------------------------------------------------------------
FROM rust-base AS xwayland-satellite-builder

WORKDIR /build

# clone xwayland-satellite
RUN git clone https://github.com/Supreeeme/xwayland-satellite.git .

# Build xwayland-satellite
RUN cargo build --release

# -----------------------------------------------------------------------------
# greetd
# -----------------------------------------------------------------------------
FROM rust-base AS greetd-builder

WORKDIR /build
RUN git clone https://git.sr.ht/~kennylevinsen/greetd .
RUN cargo build --release

# Create PAM file
RUN echo "#%PAM-1.0" > greetd.pam && \
    echo "auth       include      system-auth" >> greetd.pam && \
    echo "account    include      system-auth" >> greetd.pam && \
    echo "password   include      system-auth" >> greetd.pam && \
    echo "session    include      system-auth" >> greetd.pam

# -----------------------------------------------------------------------------
# highway
# -----------------------------------------------------------------------------
FROM c-base AS highway-builder
WORKDIR /build
RUN git clone https://github.com/google/highway.git .
RUN cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DHWY_ENABLE_EXAMPLES=OFF -DHWY_ENABLE_TESTS=OFF
RUN cmake --build build
RUN cmake --install build --prefix /install/usr

# -----------------------------------------------------------------------------
# utf8proc
# -----------------------------------------------------------------------------
FROM c-base AS utf8proc-builder
WORKDIR /build
RUN git clone https://github.com/JuliaStrings/utf8proc.git .
RUN cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
RUN cmake --build build
RUN cmake --install build --prefix /install/usr

# -----------------------------------------------------------------------------
# tllist (Internal Helper for fcft/foot)
# -----------------------------------------------------------------------------
FROM c-base AS tllist-builder
WORKDIR /build
RUN git clone https://codeberg.org/dnkl/tllist.git .
RUN meson setup build --prefix=/usr
RUN DESTDIR=/install ninja -C build install

# -----------------------------------------------------------------------------
# fcft
# -----------------------------------------------------------------------------
FROM c-base AS fcft-builder
WORKDIR /build
# Copy deps
COPY --from=tllist-builder /install /
COPY --from=utf8proc-builder /install /
RUN git clone https://codeberg.org/dnkl/fcft.git .
RUN meson setup build --prefix=/usr -Ddocs=disabled && ninja -C build
RUN DESTDIR=/install ninja -C build install

# -----------------------------------------------------------------------------
# foot
# -----------------------------------------------------------------------------
FROM c-base AS foot-builder
WORKDIR /build
# Copy deps
COPY --from=tllist-builder /install /
COPY --from=utf8proc-builder /install /
COPY --from=fcft-builder /install /
RUN git clone https://codeberg.org/dnkl/foot.git .
RUN meson setup build --prefix=/usr -Ddocs=disabled -Dtests=false && ninja -C build
RUN DESTDIR=/install ninja -C build install

# -----------------------------------------------------------------------------
# brightnessctl
# -----------------------------------------------------------------------------
FROM c-base AS brightnessctl-builder
WORKDIR /build
RUN git clone https://github.com/Hummer12007/brightnessctl.git .
RUN ./configure --prefix=/usr
RUN make
RUN make install DESTDIR=/install

# -----------------------------------------------------------------------------
# cava
# -----------------------------------------------------------------------------
FROM c-base AS cava-builder
WORKDIR /build
# Cava usually bundles iniparser logic or needs it. We installed iniparser-devel.
RUN git clone https://github.com/karlstav/cava.git .
RUN ./autogen.sh && ./configure --prefix=/usr
RUN make
RUN make install DESTDIR=/install

# -----------------------------------------------------------------------------
# Final Stage
# -----------------------------------------------------------------------------
FROM quay.io/centos-bootc/centos-bootc:stream10 AS final

ARG BUILD_FLAVOR="${BUILD_FLAVOR:-}"

# Copy artifacts from builders
COPY --from=niri-builder /build/target/release/niri /usr/bin/niri

# dms
COPY --from=dms-builder /build/core/dms /usr/bin/dms
COPY --from=dms-builder /build/quickshell /usr/share/dms/shell
COPY --from=dms-builder /build/quickshell/Modules/Greetd /usr/share/dms/greeter

COPY --from=dgop-builder /build/dgop /usr/bin/dgop
COPY --from=cliphist-builder /build/cliphist /usr/bin/cliphist
COPY --from=matugen-builder /build/target/release/matugen /usr/bin/matugen
COPY --from=wlsunset-builder /build/build/wlsunset /usr/bin/wlsunset

# glycin
COPY --from=glycin-builder /install /

# libjxl
COPY --from=libjxl-builder /install /

# quickshell
COPY --from=quickshell-builder /install /

COPY --from=tuigreet-builder /build/target/release/tuigreet /usr/bin/tuigreet

COPY --from=xwayland-satellite-builder /build/target/release/xwayland-satellite /usr/bin/xwayland-satellite

# greetd
COPY --from=greetd-builder /build/target/release/greetd /usr/bin/greetd
COPY --from=greetd-builder /build/target/release/agreety /usr/bin/agreety
COPY --from=greetd-builder /build/greetd.service /usr/lib/systemd/system/greetd.service
COPY --from=greetd-builder /build/greetd.pam /etc/pam.d/greetd

# highway
COPY --from=highway-builder /install /

# utf8proc
COPY --from=utf8proc-builder /install /

# fcft
COPY --from=fcft-builder /install /

# foot
COPY --from=foot-builder /install /

# brightnessctl
COPY --from=brightnessctl-builder /install /

# cava
COPY --from=cava-builder /install /


ARG BUILD_FLAVOR="${BUILD_FLAVOR:-}"

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/var \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build/00-base.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/var \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build/01-theme.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/var \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build/02-extras.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    /ctx/build/03-nvidia.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    /ctx/build/99-cleanup.sh

# This is handy for VM testing
# RUN usermod -p "$(echo "changeme" | mkpasswd -s)" root

RUN rm -rf /var/* && bootc container lint
